const foods = [
  // Meat & Protein
  {
    id: 1,
    name: "Chicken Breast",
    category: "meat",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    unit: "100g",
  },
  {
    id: 2,
    name: "Ground Beef (85% lean)",
    category: "meat",
    calories: 215,
    protein: 25,
    carbs: 0,
    fat: 12,
    fiber: 0,
    sugar: 0,
    unit: "100g",
  },
  {
    id: 3,
    name: "Salmon",
    category: "meat",
    calories: 208,
    protein: 25,
    carbs: 0,
    fat: 12,
    fiber: 0,
    sugar: 0,
    unit: "100g",
  },
  {
    id: 4,
    name: "Eggs",
    category: "meat",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    sugar: 1.1,
    unit: "100g",
  },
  {
    id: 5,
    name: "Tuna (canned)",
    category: "meat",
    calories: 132,
    protein: 28,
    carbs: 0,
    fat: 1.3,
    fiber: 0,
    sugar: 0,
    unit: "100g",
  },
  {
    id: 6,
    name: "Turkey Breast",
    category: "meat",
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1,
    fiber: 0,
    sugar: 0,
    unit: "100g",
  },

  // Vegetables
  {
    id: 7,
    name: "Broccoli",
    category: "vegetable",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    sugar: 1.5,
    unit: "100g",
  },
  {
    id: 8,
    name: "Spinach",
    category: "vegetable",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    unit: "100g",
  },
  {
    id: 9,
    name: "Bell Pepper",
    category: "vegetable",
    calories: 31,
    protein: 1,
    carbs: 7,
    fat: 0.3,
    fiber: 2.5,
    sugar: 4.2,
    unit: "100g",
  },
  {
    id: 10,
    name: "Carrots",
    category: "vegetable",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    unit: "100g",
  },
  {
    id: 11,
    name: "Cucumber",
    category: "vegetable",
    calories: 16,
    protein: 0.7,
    carbs: 4,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.7,
    unit: "100g",
  },
  {
    id: 12,
    name: "Tomato",
    category: "vegetable",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    unit: "100g",
  },

  // Fruits
  {
    id: 13,
    name: "Apple",
    category: "fruit",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10,
    unit: "100g",
  },
  {
    id: 14,
    name: "Banana",
    category: "fruit",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12,
    unit: "100g",
  },
  {
    id: 15,
    name: "Orange",
    category: "fruit",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    sugar: 9.4,
    unit: "100g",
  },
  {
    id: 16,
    name: "Strawberries",
    category: "fruit",
    calories: 32,
    protein: 0.7,
    carbs: 8,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    unit: "100g",
  },
  {
    id: 17,
    name: "Grapes",
    category: "fruit",
    calories: 62,
    protein: 0.6,
    carbs: 16,
    fat: 0.2,
    fiber: 0.9,
    sugar: 15,
    unit: "100g",
  },
  {
    id: 18,
    name: "Avocado",
    category: "fruit",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
    sugar: 0.7,
    unit: "100g",
  },

  // Grains & Carbs
  {
    id: 19,
    name: "Brown Rice (cooked)",
    category: "grain",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    unit: "100g",
  },
  {
    id: 20,
    name: "White Rice (cooked)",
    category: "grain",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    unit: "100g",
  },
  {
    id: 21,
    name: "Oats (dry)",
    category: "grain",
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 6.9,
    fiber: 10.6,
    sugar: 0.9,
    unit: "100g",
  },
  {
    id: 22,
    name: "Whole Wheat Bread",
    category: "grain",
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 4.2,
    fiber: 6,
    sugar: 5.4,
    unit: "100g",
  },
  {
    id: 23,
    name: "Pasta (cooked)",
    category: "grain",
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    sugar: 0.6,
    unit: "100g",
  },
  {
    id: 24,
    name: "Quinoa (cooked)",
    category: "grain",
    calories: 120,
    protein: 4.4,
    carbs: 22,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0.9,
    unit: "100g",
  },

  // Dairy
  {
    id: 25,
    name: "Milk (2%)",
    category: "dairy",
    calories: 50,
    protein: 3.3,
    carbs: 4.8,
    fat: 2,
    fiber: 0,
    sugar: 4.8,
    unit: "100ml",
  },
  {
    id: 26,
    name: "Greek Yogurt (plain)",
    category: "dairy",
    calories: 97,
    protein: 9,
    carbs: 3.6,
    fat: 5,
    fiber: 0,
    sugar: 3.6,
    unit: "100g",
  },
  {
    id: 27,
    name: "Cheddar Cheese",
    category: "dairy",
    calories: 403,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
    sugar: 0.5,
    unit: "100g",
  },
  {
    id: 28,
    name: "Cottage Cheese",
    category: "dairy",
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    sugar: 2.7,
    unit: "100g",
  },

  // Nuts & Seeds
  {
    id: 29,
    name: "Almonds",
    category: "nuts",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
    sugar: 4.4,
    unit: "100g",
  },
  {
    id: 30,
    name: "Walnuts",
    category: "nuts",
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 6.7,
    sugar: 2.6,
    unit: "100g",
  },
  {
    id: 31,
    name: "Peanut Butter",
    category: "nuts",
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    sugar: 9.2,
    unit: "100g",
  },
  {
    id: 32,
    name: "Chia Seeds",
    category: "nuts",
    calories: 486,
    protein: 17,
    carbs: 42,
    fat: 31,
    fiber: 34,
    sugar: 0,
    unit: "100g",
  },
];

// Helper function to get foods by category
const getFoodsByCategory = (category) => {
  return foods.filter((food) => food.category === category);
};

// Categories for easy reference
const categories = [
  { id: "meat", name: "Meat & Protein", icon: "🥩" },
  { id: "vegetable", name: "Vegetables", icon: "🥬" },
  { id: "fruit", name: "Fruits", icon: "🍎" },
  { id: "grain", name: "Grains & Carbs", icon: "🌾" },
  { id: "dairy", name: "Dairy", icon: "🥛" },
  { id: "nuts", name: "Nuts & Seeds", icon: "🥜" },
];

export { foods, getFoodsByCategory, categories };

/*
  const [query, setQuery] = useState("");

  const filteredItems = foods.filter((food) =>
    food.name.toLowerCase().includes(query.toLowerCase())
  );
  return (
    <div>
      <h1>food search</h1>
      <input
        type="text"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
      />

      <ul>
        {filteredItems.map((food) => (
          <div>
            {`${food.unit} of ${food.name} contains: Calories - ${food.calories}g, 
              Protein - ${food.protein}g, 
              Carbs - ${food.carbs}g, 
              Fat - ${food.fat}g, 
              Fiber - ${food.fiber}g, 
              Sugar - ${food.sugar}g`}
          </div>
        ))}
      </ul>
    </div>
  );
*/
